### PR TITLE
added support for Zabbix 3.2.x up to 3.4.1

### PR DESCRIPTION
**Pull request by PetzJohannes**
Hi,

I have compared the database schema between 3.2.0 and 3.4.1 and added the missing tables.
Maybe it is useful for you too.

Cheers

### CODE REVIEW

**Comment by ignaqui** [comment]
I've tested this on my zabbix 3.2.7 - works fine

**Comment by maxhq** [comment]
@PetzJohannes Thank you very much! I hope I soon find the time to try out and merge all open PRs.
@ignaqui Thank you for confirming.

**Comment by Woolnut** [comment]
I will be keeping an eye on this as it looks to be perfect for my needs, i'm not confident enough at the moment to modify the script myself!

**Comment by BSDUKJ** [comment]
Does this work with all 3.4.x versions? We are now on 3.4.11 and I'm looking to upgrade from 3.4.5 soon.

**Comment by PetzJohannes** [comment]
@BSDUKJ this should work yes.
You can see both database schema files here:
3.4.1: https://www.zabbix.org/websvn/wsvn/zabbix.com/tags/3.4.1/create/src/schema.tmpl
3.4.11: https://www.zabbix.org/websvn/wsvn/zabbix.com/tags/3.4.11/create/src/schema.tmpl

If you make a diff on these files you will see only two indexes and the dbversion were changed.
DB version stands on "3040007" so I think this was last changed on 3.4.7.

When your upgrade is done and you have tested the database backup successfully, please comment again so @maxhq can merge with 3.4.11 tested.

**Comment by TomaszDom** [comment]
Any progress on this? @BSDUKJ ?

**Comment by bercerobry** [comment]
Is this good for Zabbix Server v3.4.13 ?

**Comment by maxhq** [comment]
Thank you @PetzJohannes for the update and everybody else for testing and commenting. As there was a newer PR meanwhile I will close this one.

**Pull request closed without merging**
