### PR TITLE
Add postgres dump

### PR DESCRIPTION
**Pull request by sergeygalkin**
Hi
I have added dump for postgresql 
Tested on my zabbix 3.0.0 and postgresql 9.6.2
but I have not tested with mysql

### CODE REVIEW

**Comment by maxhq** [comment]
Very nice @sergeygalkin - it's great to have an additional database covered.
One thing: people might not be happe if the script changes their config file. Could you change the script to put the config into a temp file `PWFILE=$(mktemp)` and set `PGPASSFILE=$PWFILE`. Does that work for you?

**Comment by sergeygalkin** [comment]
@maxhq make sense. I have added and tested.

**Comment by endersonmaia** [comment]
I'd suggest a `sqash` to keep history clean.

**Comment by sergeygalkin** [comment]
@endersonmaia make sense

**Comment by endersonmaia** [comment]
@sergeygalkin you could make a `git rebase -i master` from your functional branch and `git push --force`to the remote branch you're using to this PR, but it seems that you don't have a public github fork for the project, is that right ?

**Comment by sergeygalkin** [comment]
@endersonmaia  I have created https://github.com/maxhq/zabbix-backup/pull/11 from my new   https://github.com/sergeygalkin/zabbix-backup.  I can't create single commit pull request in this pull request

**Pull request closed without merging**
